/**
 * Array.prototype.sort
 *
 * - Сортирует исходный массив (in-place)
 * - Принимает функцию-компаратор (англ. compare - сравнивать)
 * - Если нет компаратора - сортирует элементы как строки
 */

const numbers = [91, 13, 2, -42, 0, 55, 111];
const users = [
  {
    id: 1,
    first_name: 'Dulcea',
    last_name: 'Hartzogs',
    gender: 'Female',
    message_count: 0,
  },
  {
    id: 2,
    first_name: 'Kipp',
    last_name: 'MacGuiness',
    email: 'kmacguiness1@storify.com',
    gender: 'Male',
    message_count: 2,
  },
  {
    id: 3,
    first_name: 'Desirae',
    last_name: 'Thickett',
    email: 'dthickett2@nhs.uk',
    gender: 'Female',
    message_count: 82,
  },
  {
    id: 4,
    first_name: 'Perl',
    last_name: 'Ironside',
    email: 'pironside3@tinypic.com',
    gender: 'Female',
    message_count: 73,
  },
  {
    id: 5,
    first_name: 'Dolph',
    last_name: 'Skullet',
    email: 'dskullet4@yelp.com',
    gender: 'Male',
    message_count: 60,
  },
  {
    id: 6,
    first_name: 'Stephanus',
    last_name: 'Danko',
    email: 'sdanko5@nydailynews.com',
    gender: 'Male',
    message_count: 6,
  },
  {
    id: 7,
    first_name: 'Whit',
    last_name: 'Widdup',
    email: 'wwiddup6@woothemes.com',
    gender: 'Male',
    message_count: 19,
  },
  {
    id: 8,
    first_name: 'Maurizio',
    last_name: 'Grewe',
    email: 'mgrewe7@microsoft.com',
    gender: 'Male',
    message_count: 66,
  },
  {
    id: 9,
    first_name: 'Callie',
    last_name: 'Ternent',
    email: 'cternent8@csmonitor.com',
    gender: 'Female',
    message_count: 46,
  },
  {
    id: 10,
    first_name: 'Kirby',
    last_name: 'Stallen',
    email: 'kstallen9@etsy.com',
    gender: 'Male',
    message_count: 36,
  },
  {
    id: 11,
    first_name: 'Angelina',
    last_name: 'Crawcour',
    email: 'acrawcoura@desdev.cn',
    gender: 'Female',
    message_count: 53,
  },
  {
    id: 12,
    first_name: 'Courtnay',
    last_name: 'Cockerton',
    email: 'ccockertonb@cloudflare.com',
    gender: 'Female',
    message_count: 64,
  },
  {
    id: 13,
    first_name: 'Dugald',
    last_name: 'Dyerson',
    email: 'ddyersonc@auda.org.au',
    gender: 'Male',
    message_count: 22,
  },
  {
    id: 14,
    first_name: 'Mavis',
    last_name: 'Lugg',
    email: 'mluggd@free.fr',
    gender: 'Female',
    message_count: 61,
  },
  {
    id: 15,
    first_name: 'Ollie',
    last_name: 'Yeoman',
    email: 'oyeomane@yelp.com',
    gender: 'Male',
    message_count: 23,
  },
  {
    id: 16,
    first_name: 'Dyane',
    last_name: 'Tuppeny',
    email: 'dtuppenyf@cisco.com',
    gender: 'Female',
    message_count: 76,
  },
  {
    id: 17,
    first_name: 'Joyous',
    last_name: 'Lambersen',
    email: 'jlamberseng@prlog.org',
    gender: 'Female',
    message_count: 72,
  },
  {
    id: 18,
    first_name: 'Salome',
    last_name: 'Bissett',
    email: 'sbissetth@bing.com',
    gender: 'Female',
    message_count: 54,
  },
  {
    id: 19,
    first_name: 'Audre',
    last_name: 'Ciubutaro',
    email: 'aciubutaroi@delicious.com',
    gender: 'Female',
    message_count: 99,
  },
  {
    id: 20,
    first_name: 'Linnea',
    last_name: 'Proffitt',
    email: 'lproffittj@pen.io',
    gender: 'Female',
    message_count: 76,
  },
  {
    id: 21,
    first_name: 'Jayson',
    last_name: 'MacSorley',
    email: 'jmacsorleyk@vimeo.com',
    gender: 'Male',
    message_count: 80,
  },
  {
    id: 22,
    first_name: 'Shandra',
    last_name: 'Gadney',
    email: 'sgadneyl@home.pl',
    gender: 'Female',
    message_count: 62,
  },
  {
    id: 23,
    first_name: 'Benny',
    last_name: 'Firmager',
    email: 'bfirmagerm@europa.eu',
    gender: 'Female',
    message_count: 98,
  },
  {
    id: 24,
    first_name: 'Vincenty',
    last_name: 'Mumm',
    email: 'vmummn@netscape.com',
    gender: 'Male',
    message_count: 0,
  },
  {
    id: 25,
    first_name: 'Merilyn',
    last_name: 'Leming',
    email: 'mlemingo@phpbb.com',
    gender: 'Female',
    message_count: 87,
  },
  {
    id: 26,
    first_name: 'Zolly',
    last_name: 'Henriquet',
    email: 'zhenriquetp@seesaa.net',
    gender: 'Male',
    message_count: 81,
  },
  {
    id: 27,
    first_name: 'Darleen',
    last_name: 'Gully',
    email: 'dgullyq@usa.gov',
    gender: 'Female',
    message_count: 58,
  },
  {
    id: 28,
    first_name: 'Norina',
    last_name: 'Durban',
    email: 'ndurbanr@chron.com',
    gender: 'Female',
    message_count: 22,
  },
  {
    id: 29,
    first_name: 'Reamonn',
    last_name: 'Sommerland',
    email: 'rsommerlands@networkadvertising.org',
    gender: 'Male',
    message_count: 7,
  },
  {
    id: 30,
    first_name: 'Redford',
    last_name: 'Garstang',
    email: 'rgarstangt@bloglines.com',
    gender: 'Male',
    message_count: 37,
  },
  {
    id: 31,
    first_name: 'Lisette',
    last_name: 'Grandison',
    email: 'lgrandisonu@flickr.com',
    gender: 'Female',
    message_count: 1,
  },
  {
    id: 32,
    first_name: 'Becka',
    last_name: 'Rubie',
    email: 'brubiev@pen.io',
    gender: 'Female',
    message_count: 51,
  },
  {
    id: 33,
    first_name: 'Raimundo',
    last_name: 'Smithin',
    email: 'rsmithinw@archive.org',
    gender: 'Male',
    message_count: 33,
  },
  {
    id: 34,
    first_name: 'Johannah',
    last_name: 'Koppens',
    email: 'jkoppensx@feedburner.com',
    gender: 'Female',
    message_count: 92,
  },
  {
    id: 35,
    first_name: 'Stacee',
    last_name: 'Pollock',
    email: 'spollocky@businesswire.com',
    gender: 'Female',
    message_count: 47,
  },
  {
    id: 36,
    first_name: 'Dav',
    last_name: 'McDonnell',
    email: 'dmcdonnellz@biglobe.ne.jp',
    gender: 'Male',
    message_count: 73,
  },
  {
    id: 37,
    first_name: 'Rich',
    last_name: 'Mardlin',
    email: 'rmardlin10@themeforest.net',
    gender: 'Male',
    message_count: 12,
  },
  {
    id: 38,
    first_name: 'Shelagh',
    last_name: 'Courteney',
    email: 'scourteney11@omniture.com',
    gender: 'Female',
    message_count: 37,
  },
  {
    id: 39,
    first_name: 'Lilian',
    last_name: 'Foakes',
    email: 'lfoakes12@admin.ch',
    gender: 'Female',
    message_count: 43,
  },
  {
    id: 40,
    first_name: 'Elliott',
    last_name: 'Spaight',
    email: 'espaight13@sohu.com',
    gender: 'Male',
    message_count: 47,
  },
  {
    id: 41,
    first_name: 'Birch',
    last_name: 'Pashan',
    email: 'bpashan14@cnet.com',
    gender: 'Male',
    message_count: 60,
  },
  {
    id: 42,
    first_name: 'Eula',
    last_name: 'Easterbrook',
    email: 'eeasterbrook15@usnews.com',
    gender: 'Female',
    message_count: 71,
  },
  {
    id: 43,
    first_name: 'Jens',
    last_name: 'Pic',
    email: 'jpic16@omniture.com',
    gender: 'Male',
    message_count: 96,
  },
  {
    id: 44,
    first_name: 'Sergei',
    last_name: 'Cheal',
    email: 'scheal17@addtoany.com',
    gender: 'Male',
    message_count: 59,
  },
  {
    id: 45,
    first_name: 'Whitney',
    last_name: 'Bernardot',
    email: 'wbernardot18@discuz.net',
    gender: 'Female',
    message_count: 23,
  },
  {
    id: 46,
    first_name: 'Etti',
    last_name: 'Hitzmann',
    email: 'ehitzmann19@imgur.com',
    gender: 'Female',
    message_count: 90,
  },
  {
    id: 47,
    first_name: 'Wilhelm',
    last_name: 'Dinning',
    email: 'wdinning1a@t.co',
    gender: 'Male',
    message_count: 23,
  },
  {
    id: 48,
    first_name: 'Shoshana',
    last_name: 'Hanlon',
    email: 'shanlon1b@about.com',
    gender: 'Female',
    message_count: 19,
  },
  {
    id: 49,
    first_name: 'Jamie',
    last_name: 'Redfield',
    email: 'jredfield1c@weibo.com',
    gender: 'Female',
    message_count: 5,
  },
  {
    id: 50,
    first_name: 'Trueman',
    last_name: 'Perkinson',
    email: 'tperkinson1d@weebly.com',
    gender: 'Male',
    message_count: 20,
  },
];

Array.from(numbers).sort((a, b) => {
  return a - b;
});

[...users].sort((a, b) => a.first_name.localeCompare(b.first_name));

// console.log(numbers);
console.table(users);
